name: flutter_loro_ffi_example
description: Demonstrates how to use the flutter_loro_ffi plugin.

publish_to: 'none' # 防止意外发布到pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_loro_ffi:
    # 当发布到pub.dev时，指定版本
    # version: 0.1.0
    # 开发时使用本地路径
    path: ../

  # 以下是Flutter应用常用依赖
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true