name: loro_dart
description: Flutter plugin for Loro FFI bindings
version: 1.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"

homepage: https://github.com/alexcdever/loro-dart
repository: https://github.com/alexcdever/loro-dart

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  benchmark_harness: ^2.2.0
  test: ^1.26.3

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      linux:
        ffiPlugin: true