language = "C"
header = "/* Loro FFI Bindings */"
include_guard = "LORO_FFI_H"
include_version = false
namespace = "loro_ffi"
style = "both"

[export]
include = ["LoroDoc"]
prefix = "loro"
item_types = ["globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]